spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring_cafe
    driver-class-name: org.h2.Driver
    username: sa